apiVersion: apps/v1
kind: Deployment
metadata:
  name: webnotepad-deployment
  labels:
    app: webnotepad-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webnotepad-app
  template:
    metadata:
      labels:
        app: webnotepad-app
    spec:
      containers:
        - name: webnotepad-app
          image: IMAGE_PLACEHOLDER  # Замените на ваш образ
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: webnotepad-app-svc
spec:
  type: NodePort
  selector:
    app: webnotepad-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007
